### PR TITLE
Fix coverage version to 5.x

### LINKED ISSUE #13: Incompatible with coverage 6.0.0
**Describe the bug**
A clear and concise description of the bug.

The coverage bade package is incompatible with coverage version 6.0.0. 
The following attribute error `AttributeError: 'Precision' object has no attribute '_near0'` is observed if coverage 6.0.0 is used 

**To Reproduce**
How can we reproduce the problem?  Please *be specific*. Don't just link to a failing CI job. Answer the questions below:
1. What version of Python are you using? 
`3.8.5`

1. What version of coverage.py are you using? The output of `coverage debug sys` is helpful.
```
-- sys -------------------------------------------------------
               coverage_version: 6.0
                coverage_module: /Users/max/anaconda3/lib/python3.8/site-packages/coverage/__init__.py
                         tracer: -none-
                        CTracer: available
           plugins.file_tracers: -none-
            plugins.configurers: -none-
      plugins.context_switchers: -none-
              configs_attempted: .coveragerc
                                 setup.cfg
                                 tox.ini
                                 pyproject.toml
                   configs_read: /Users/max/dwh-partner-config/setup.cfg
                                 /Users/max/dwh-partner-config/pyproject.toml
                    config_file: None
                config_contents: -none-
                      data_file: -none-
                         python: 3.8.5 (default, Sep  4 2020, 02:22:02) [Clang 10.0.0 ]
                       platform: macOS-10.16-x86_64-i386-64bit
                 implementation: CPython
                     executable: /Users/max/anaconda3/bin/python
                   def_encoding: utf-8
                    fs_encoding: utf-8
                            pid: 21446
                            cwd: /Users/max/dwh-partner-config
                           path: /Users/max/anaconda3/bin
                                 /Users/max/anaconda3/lib/python38.zip
                                 /Users/max/anaconda3/lib/python3.8
                                 /Users/max/anaconda3/lib/python3.8/lib-dynload
                                 /Users/max/anaconda3/lib/python3.8/site-packages
                                 /Users/max/anaconda3/lib/python3.8/site-packages/aeosa
                    environment: CONDA_PYTHON_EXE = /Users/max/anaconda3/bin/python
                                 HOME = /Users/max
                   command_line: /Users/max/anaconda3/bin/coverage debug sys
                sqlite3_version: 2.6.0
         sqlite3_sqlite_version: 3.33.0
             sqlite3_temp_store: 0
        sqlite3_compile_options: COMPILER=clang-10.0.0; ENABLE_COLUMN_METADATA; ENABLE_DBSTAT_VTAB
                                 ENABLE_FTS3; ENABLE_FTS3_TOKENIZER; ENABLE_FTS4
                                 ENABLE_FTS5; ENABLE_GEOPOLY; ENABLE_JSON1
                                 ENABLE_RTREE; ENABLE_UNLOCK_NOTIFY; MAX_DEFAULT_PAGE_SIZE=32768
                                 MAX_EXPR_DEPTH=10000; MAX_VARIABLE_NUMBER=250000; SECURE_DELETE
                                 THREADSAFE=1
```

1. What versions of what packages do you have installed? The output of `pip freeze` is helpful.
The coverage-badge version is `1.0.1`

1. What code are you running?  Give us a specific commit of a specific repo that we can check out.
`coverage-badge -o coverage.svg` inside the root of repo after the `.coverage/` has been generated.

**Expected behavior**

I expect the package to handle both versions of `coverage` (5.x.x and 6). 
All works fine when coverage is reverted back to `coverage==5.3.0`

**Additional context**

### PR DESCRIPTION
**Pull request by astariul**
Fix #13 

---

This PR just fix the version of `coverage` to `5.x`, so it doesn't break anymore

### CODE REVIEW

**Comment by ryan-cpi** [comment]
This seems to work for us thanks. Can you add @dbrgn as a reviewer to this PR?

**Comment by dbrgn** [comment]
I don't know if 5.x is compatible with 6.x-generated coverage files, but if it works, that's fine for me!

Thanks for the fix, @astariul.

**Comment by nedbat** [comment]
This seems like an unfortunate way to fix this problem....

**Comment by astariul** [comment]
@nedbat Why so ?

`coverage` is just a dependency, and dependencies have breaking changes all the time. Pinning the dependency to a specific version allow usage of this package without errors (introduced by the breaking change of a dependency).

Of course it means we will not have access to the latest features of `coverage` package, but anyway [the author mentioned he is not maintaining this package anymore](https://github.com/dbrgn/coverage-badge/issues/13#issuecomment-933893157).

---

Of course you can also open a PR fixing the issue for `coverage` version 6.x, and that's the logical next step. But in the meantime, this fix is perfectly valid.

**Comment by dbrgn** [comment]
@nedbat What @astariul wrote. In the meantime, someone has already sent a PR for compatibility with both 5.x and 6.x at #17 🙂

**Pull request merged**
