### PR TITLE
Different color badges

### PR DESCRIPTION
**Pull request by Samael500**
Change color of badge by coverage result.
Also add `-f` flag to force overwrite output path.

### CODE REVIEW

**Comment by dbrgn** [comment]
Sorry for not responding earlier. I somehow missed this PR.

Awesome change, thanks @Samael500! :)

There's a last request I have - would you mind adding an option to manually override the color to a fixed value? Some people might prefer static colors.

**Comment by Samael500** [comment]
Add `-p` flag for plain color mode.

**Comment by dbrgn** [comment]
Thanks!

**Comment by dbrgn** [comment]
PyPI release will follow tonight.

**Comment by dbrgn** [comment]
Version 0.2.0 is released: https://pypi.python.org/pypi/coverage-badge/0.2.0

**Pull request merged**
