### PR TITLE
setuptools is needed to provide pkg_resources

### PR DESCRIPTION
**Pull request by AdrienPensart**
setuptools seems to be needed in order to provide pkg_resources, this PR will fix that, so users don't need to add setuptools themselves.

### CODE REVIEW

**Comment by dbrgn** [comment]
Hm, the requirement on setuptools is defined inside the call to `setuptools.setup`. Will this really help?

**Comment by Bilbottom** [comment]
This also impacts me so I'm in favour of this PR

I use [Poetry](https://python-poetry.org/) for package management and installing the dependencies doesn't include `setuptools`, presumably because Poetry uses [a different build backend](https://python-poetry.org/docs/pyproject/#poetry-and-pep-517)

---

- Python version: `3.11.5`
- coverage-badge version: `1.1.1`
- Poetry version: `1.8.0`
  - Build backend: `poetry.core.masonry.api`

**Comment by dbrgn** [comment]
Again: The requirement on setuptools is defined inside the call to `setuptools.setup`. Will this really help?

To me, it looks like the PR won't actually solve the issue.

**Comment by Bilbottom** [comment]
> Again: The requirement on setuptools is defined inside the call to `setuptools.setup`. Will this really help?
> 
> To me, it looks like the PR won't actually solve the issue.

In my case, Poetry doesn't need `setuptools` so [it won't install it unless it's explicitly added as a dependency](https://python-poetry.org/docs/configuration/#virtualenvsoptionsno-setuptools):

image

I've "fixed" my downstream repos by adding `setuptools` as a dependency, but since this project assumes that `setuptools` is available inside the source code, this PR would ensure that `setuptools` exists regardless of how the package is installed by its users 🙂

**Comment by dbrgn** [comment]
Ah, so I guess some tools don't actually evaluate the script, but will instead have their own pseudo-setuptools implementation.

I guess it doesn't hurt to include it, so I'll merge this.

**Pull request merged**
